FROM postgres:16-alpine
COPY entrypoint-replica.sh /usr/local/bin/entrypoint-replica.sh
RUN chmod +x /usr/local/bin/entrypoint-replica.sh
ENTRYPOINT ["/usr/local/bin/entrypoint-replica.sh"]
CMD ["postgres"]
